server {
  listen 80;
  root /usr/share/nginx/html;
  location /api/ {
    proxy_pass http://api:4000;
    proxy_buffering off;
    proxy_read_timeout 300s;
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
